### ISSUE TITLE
Create a tutorial for running Kubernetes on DCOS

### ISSUE THREAD

**Issue by k82cn** [dcos/dcos-docs#621]
Transfer the requirement to the right repo :).

https://github.com/kubernetes/kubernetes/issues/9260

/cc @guenter , @jmheidly,  @justinclayton

**Comment by karlkfi** [comment]
The k8s-mesos project has now been taken over by IBM. They are currently focussing on the Mesos compatibility, afaik. k8s-mesos has not worked on DC/OS since DC/OS 1.5 (prior to it being open sourced). It is unlikely that k8s will work on DC/OS in the near future for several reasons related to the design of the k8s-mesos integration and constraints within DC/OS.

DC/OS will also have Pods in v1.9. So they're not a lot of motivation to invest in k8s on DC/OS. If that changes at some point in the future, this ticket can be re-openned or re-created.

**Comment by karlkfi** [comment]
The k8s-mesos project has been extracted fromt he upstream k8s repo and moved to https://github.com/kubernetes-incubator/kube-mesos-framework

**Comment by mhausenblas** [comment]
What @karlkfi said. However, if and when K8S on DC/OS is available (again) we should definitely pick this one up. All DC/OS issues should be filed against https://dcosjira.atlassian.net/
